FROM golang:1.19.1 as build
RUN apt-get update && apt-get install -y \
	curl \
	git \
	libpq-dev \
	postgresql \
	postgresql-client \
	postgresql-contrib \
	sudo \
	vim \
	supervisor \
	nginx \
	cron

RUN addgroup --system stellar && adduser --system -uid 10011001 stellar
RUN mkdir -p /opt/stellar/bin /opt/stellar/www /opt/stellar/postgresql/data
WORKDIR /home/stellar
COPY --chown=stellar:stellar . .

WORKDIR ./services/ticker/docker/
RUN cp -r conf /opt/stellar/conf
RUN crontab -u stellar /opt/stellar/conf/crontab.txt
RUN chmod +x start
WORKDIR /home/stellar/services/ticker
RUN cp issuers.txt /opt/stellar/conf
RUN go build -buildvcs=false -o /opt/stellar/bin/ticker .

RUN chown -R stellar:stellar /opt/stellar

EXPOSE 5432
EXPOSE 8000

ENTRYPOINT ["./docker/start"]
